# Generated by Django 4.0.3 on 2022-03-18 08:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(choices=[('Principal', 'Principal'), ('Vice-Principal', 'Vice-Principal'), ('Admin', 'Admin')], default='Principal', max_length=50)),
                ('date_of_issue', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('roll_no', models.IntegerField(default='10', primary_key=True, serialize=False)),
                ('registration_number', models.CharField(default='00000P', max_length=20)),
                ('fathers_name', models.CharField(max_length=255)),
                ('mothers_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('cls', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default=10, max_length=10)),
                ('date_of_birth', models.DateField(default=datetime.date.today)),
                ('character_of_student', models.CharField(choices=[('Outstanding', 'Outstanding'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Average', 'Average')], default='Good', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'students',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cls', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default=10, max_length=10)),
                ('subject_code', models.CharField(max_length=10)),
                ('credit_hour', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_point', models.FloatField(max_length=10)),
                ('grade', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D'), ('NG', 'NG')], default='A+', max_length=10)),
                ('final_grade', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D'), ('NG', 'NG')], default='A+', max_length=10)),
                ('remarks', models.CharField(max_length=40)),
                ('date_of_result', models.DateField(default=datetime.date.today)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.subject')),
            ],
        ),
    ]
