# Generated by Django 4.0.3 on 2022-03-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='character_of_student',
            field=models.CharField(choices=[('Theory', 'Theory'), ('Practical', 'Practical')], default='Good', max_length=50),
        ),
    ]
